" BASIC
set nocompatible " No vi compatility, this first because it resets some options
set mouse=a
set cb=autoselect
let mapleader="," " Mapleader
filetype off
set encoding=utf-8
set history=1000  " Keep more history, default is 20

set runtimepath^=~/.vim/bundle/repos/github.com/Shougo/dein.vim

call dein#begin('~/.vim/bundle')

call dein#add('Shougo/dein.vim')
call dein#add('scrooloose/nerdtree')
call dein#add('altercation/vim-colors-solarized')
call dein#add('dkprice/vim-easygrep')
call dein#add('/usr/local/opt/fzf')
call dein#add('junegunn/fzf.vim')

call dein#add('tpope/vim-endwise')
call dein#add('tpope/vim-fugitive')
call dein#add('tpope/vim-unimpaired')
call dein#add('tpope/vim-commentary')

" Languages
call dein#add('gabrielelana/vim-markdown')
call dein#add('tpope/vim-rails')
call dein#add('vim-ruby/vim-ruby')
call dein#add('kchmck/vim-coffee-script')
call dein#add('pangloss/vim-javascript')
call dein#add('fatih/vim-go')
call dein#add('nvie/vim-flake8')
call dein#add('davidhalter/jedi-vim')

if dein#check_install()
  call dein#install()
  let pluginsExist=1
endif

call dein#end()

filetype plugin indent on


" Allow editing crontabs http://vim.wikia.com/wiki/Editing_crontab
set backupskip=/tmp/*,/private/tmp/* "
set undodir=~/.vim/undo
set noswapfile
set nobackup

let python_highlight_all=1
syntax enable
set background=dark " Set dark solarized theme
colorscheme solarized
set t_Co=256  " 2000s plz
set scrolloff=5   " Keep some distance to the bottom"
set showmatch     " Show matching of: () [] {}
set ignorecase    " Required for smartcase to work
set smartcase     " Case sensitive when uppercase is present
set incsearch     " Search as you type
set smartindent   " Be smart about indentation
set expandtab     " Tabs are spaces
set smarttab
set shell=$SHELL\ -l  " load shell for ruby version etc.
set ruler

set tabstop=2 " Tabs are 2 spaces
set backspace=2 " Backspace deletes 2 spaces
set shiftwidth=2 " Even if there are tabs, preview as 2 spaces

set number
set clipboard=unnamed

set list " Highlight trailings, stolen from @teoljungberg
set listchars=tab:>-,trail:.,extends:>,precedes:<

set tags=tags,.git/tags " Use commit hook tags, see ~/.git_template

set backspace=indent,eol,start

" Fuzzy finder
let g:fzf_buffers_jump = 1
map <C-f> <plug>(fzf-complete-line)
map <leader>t :Files<CR>
map <leader>g :Tags<CR>

" NERDTree
map ` :NERDTreeToggle<cr>
map <leader>l :NERDTreeFind<CR>
let NERDTreeIgnore = ['\.pyc$']

" Git
map <leader>gs :Gstatus<CR>
map <leader>gc :Gcommit<CR>
map <leader>gb :Gblame<CR>
map <leader>gd :Gdiff<CR>
map <leader>gs :Gstatus<CR>

au BufNewFile,BufRead *.ejson set filetype=json

au FileType python setlocal tabstop=4 softtabstop=4 shiftwidth=4 autoindent fileformat=unix

autocmd BufNewFile,BufRead *.md,*.markdown set spell

autocmd FileType go,gitcommit,qf,gitset setlocal nolist " Go fmt will use tabs

set wildignore+=.git/**,public/assets/**,vendor/**,log/**,tmp/**,Cellar/**,app/assets/images/**,_site/**,home/.vim/bundle/**,**/.gitkeep,**/.DS_Store,**/*.netrw*,node_modules/*

autocmd Syntax c,cpp,vim,xml,html,xhtml setlocal foldmethod=syntax
autocmd Syntax c,cpp,vim,xml,html,xhtml normal zR

" Search
command! -nargs=+ Search silent execute "Grep <args>" | redraw! | cw
nnoremap <leader>f :Search<space>

" bind F to grep for the word under the cursor
map <silent> F <plug>EgMapGrepCurrentWord_v
vmap <silent> F <plug>EgMapGrepSelection_v

let g:EasyGrepRecursive=1

map <C-f> <PageDown>

"python with virtualenv support
py << EOF
import os
import sys
if 'VIRTUAL_ENV' in os.environ:
  project_base_dir = os.environ['VIRTUAL_ENV']
  activate_this = os.path.join(project_base_dir, 'bin/activate_this.py')
  execfile(activate_this, dict(__file__=activate_this))
EOF

if exists('$TMUX')
  let &t_SI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=1\x7\<Esc>\\"
  let &t_EI = "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"

  "autocmd VimLeave * :!echo -ne "\<Esc>Ptmux;\<Esc>\<Esc>]50;CursorShape=0\x7\<Esc>\\"
else
  let &t_SI = "\<Esc>]50;CursorShape=1\x7"
  let &t_EI = "\<Esc>]50;CursorShape=0\x7"

  if &term =~ "xterm\\|rxvt"
    " Changes the cursor between a Block and Line when in Insert mode or not.
    " These escape codes only work in iTerm2
    let &t_SI = "\<Esc>]50;CursorShape=1\x7"
    let &t_EI = "\<Esc>]50;CursorShape=0\x7"
    autocmd VimLeave * :!echo -ne "\<Esc>]50;CursorShape=0\x7"
  endif
endif
